# Generated by Django 5.2.10 on 2026-02-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_alert',
            field=models.BooleanField(default=False),
        ),
    ]
