# Generated by Django 5.2.10 on 2026-02-09 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_created_at_cartitem_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_activity_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
