# Generated by Django 5.2.10 on 2026-02-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_orde_custome_59b6fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_payment_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
