# Generated by Django 5.2.10 on 2026-02-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_critical_stock_alert_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
