# Generated by Django 5.2.10 on 2026-02-10 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_first_name_and_more'),
        ('products', '0007_product_low_stock_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity when the product was first created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_cannot_be_negative'),
        ),
    ]
