# Generated by Django 5.2.10 on 2026-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_initial_stock_alter_product_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity when the product was first created'),
        ),
    ]
