"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv
import cloudinary
import environ
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from core.log_configs.logging_context import before_send

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'rest_framework',
    'cloudinary',
    'cloudinary_storage',
    'drf_spectacular',
    
    # apps
    'accounts',
    'products',
    'cart',
    'payments',
    'orders',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.LoggingContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'

if not DEBUG:

    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Accounts
        "login": "5/min",
        "register": "3/min",
        "email_verify": "10/min",
        
        # Authenticated user actions
        "user_update": "20/min",
        "user_read": "60/min",
        
        # Bank
        "bank_create": "3/min",
        "bank_update": "5/min",
        "bank_read": "30/min",
        "bank_delete": "10/min",
        
        # Vendor
        "vendor_create": "5/min",
        "vendor_update": "20/min",
        "vendor_read": "60/min",
        "vendor_delete": "10/min",
        
        # Carts
        "cart_read": "150/min",
        "cart_history": "50/min",
        
        # Cart Items
        "cartitem_read": "120/min",
        "cartitem_create": "40/min",
        "cartitem_update": "60/min",
        "cartitem_delete": "40/min",
        
        # Checkout
        "checkout_read": "60/min",
        "checkout_history": "30/min",
        "checkout_update": "20/min",
        "checkout_confirm": "10/min",
        
        # Orders
        "order_read": "60/min",
        "order_create": "5/min",
        
        # Payments
        "payment_read": "60/min",
        "payment_initiate": "5/min",
        "payment_confirm": "10/hour",
        
        # Categories
        "category_read": "200/min",
        "category_write": "20/min",
        
        # Products
        "product_read": "300/min",
        "product_create": "30/min",
        "product_update": "40/min",
        "product_delete": "10/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=45),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    # Security
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    # Auth header
    "AUTH_HEADER_TYPES": ("Bearer",),
    "UPDATE_LAST_LOGIN": True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "StockBridge API",
    "DESCRIPTION": "Scalable E-commerce Backend API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    integrations=[DjangoIntegration()],
    before_send=before_send,
    environment=os.getenv("ENVIRONMENT", "development"),
    release=os.getenv("RELEASE_VERSION"),
    traces_sample_rate=1.0 if os.getenv("ENVIRONMENT") == "development" else 0.05,  # performance monitoring
    send_default_pii=True,  # allows user info
)

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    integrations=[
        DjangoIntegration(),
        CeleryIntegration(),
    ],
    traces_sample_rate=0.2,
    send_default_pii=True,
)

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 24 * 60 * 60  # one day
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Strict"

# Cloudinary SDK config
cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET')
)

# Django storage backend
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=not DEBUG,  # production-safe
    )
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL"), 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 5,
            }
        }
    }
}

CELERY_BROKER_POOL_LIMIT = 1
CELERY_REDIS_MAX_CONNECTIONS = 2
CELERY_RESULT_BACKEND = None  
CELERYD_HIJACK_ROOT_LOGGER = False

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

if not DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,

        "formatters": {
            "json": {
                "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
                "format": (
                    "%(levelname)s "
                    "%(asctime)s "
                    "%(name)s "
                    "%(message)s "
                    "%(request_id)s "
                    "%(user_id)s "
                ),
            },
        },

        "filters": {
            "request_user": {
                "()": "core.log_configs.logging_filters.RequestUserFilter",
            },
        },

        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "json",
                "filters": ["request_user"],
            },
        },

        # Root logger only
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
    }

else:
    LOG_DIR = BASE_DIR / "logs"
    LOG_DIR.mkdir(exist_ok=True)

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "json": {
                "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
                "format": "%(levelname)s %(asctime)s %(name)s %(message)s %(request_id)s %(user_id)s",
            },
            "verbose": {
                "format": "[{levelname}] {asctime} {process:d} {name}: {message}",
                "style": "{",
            },
        },
        
        "filters": {
            "info_only": {
                "()": "core.log_configs.logging_filters.InfoOnlyFilter",
            },
            "request_user": {
                "()": "core.log_configs.logging_filters.RequestUserFilter",
            },
        },
        
        # ROOT LOGGER (global fallback)
        "root": {
            "handlers": ["console", "app_file", "app_error_file"],
            "level": "INFO",
        },
        
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "json",
                "filters": ["request_user"],
            },
            "app_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "app.log",
                "maxBytes": 5 * 1024 * 1024,
                "backupCount": 5,
                "formatter": "json",
                "level": "INFO",
                "filters": ["info_only", "request_user"],
            },
            "app_error_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "app_errors.log",
                "maxBytes": 5 * 1024 * 1024,
                "backupCount": 5,
                "formatter": "json",
                "level": "ERROR",
                "filters": ["request_user"],
            },
        },
        
        # Optional named loggers
        "loggers": {
            "django.utils.autoreload": {
                "handlers": ["console"],
                "level": "INFO", 
                "propagate": False,
            },
            "urllib3.connectionpool": {
                "handlers": ["console"],
                "level": "INFO", 
                "propagate": False,
            },
            # Each specific apps
            # "accounts": {
            #     "handlers": ["console", "app_file", "app_error_file"],
            #     "level": "INFO",
            #     "propagate": False,
            # },
            # "cart": {
            #     "handlers": ["console", "app_file", "app_error_file"],
            #     "level": "INFO",
            #     "propagate": False,
            # },
            # "core": {
            #     "handlers": ["console", "app_file", "app_error_file"],
            #     "level": "INFO",
            #     "propagate": False,
            # },
            # "orders": {
            #     "handlers": ["console", "app_file", "app_error_file"],
            #     "level": "INFO",
            #     "propagate": False,
            # },
            # "payments": {
            #     "handlers": ["console", "app_file", "app_error_file"],
            #     "level": "INFO",
            #     "propagate": False,
            # },
            # "products": {
            #     "handlers": ["console", "app_file", "app_error_file"],
            #     "level": "INFO",
            #     "propagate": False,
            # },
        },
    }

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

AUTH_USER_MODEL = 'accounts.CustomUser'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

CART_TTL_HOURS = int(os.getenv("CART_TTL_HOURS"))
CHECKOUT_TTL_HOURS = int(os.getenv("CHECKOUT_TTL_HOURS"))
ORDER_PAYMENT_TTL_HOURS = int(os.getenv("ORDER_PAYMENT_TTL_HOURS"))
PAYMENT_REMINDER_24H_TTL_HOURS = int(os.getenv("PAYMENT_REMINDER_24H_TTL_HOURS"))
FINAL_PAYMENT_REMINDER_TTL_HOURS_START = int(os.getenv("FINAL_PAYMENT_REMINDER_TTL_HOURS_START"))
FINAL_PAYMENT_REMINDER_TTL_HOURS_END = int(os.getenv("FINAL_PAYMENT_REMINDER_TTL_HOURS_END"))
CRITICAL_INACTIVITY_HOURS = int(os.getenv("CRITICAL_INACTIVITY_HOURS"))

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DJANGO_API_URL = os.getenv("DJANGO_API_URL")
MAIL_API_URL = os.getenv("MAIL_API_URL")