# Generated by Django 5.2.10 on 2026-02-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
