# Generated by Django 5.2.10 on 2026-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
