# Generated by Django 5.2.10 on 2026-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='verified',
        ),
        migrations.AddField(
            model_name='vendor',
            name='activation_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='review_status',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved')], default='UNDER_REVIEW', max_length=20),
        ),
    ]
