# Generated by Django 5.2.10 on 2026-03-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_vendor_verified_vendor_activation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='subaccount_code',
        ),
    ]
