# Generated by Django 5.2.10 on 2026-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bankaccount_bank_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='verified',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
